// Mocks generated by Mockito 5.4.6 from annotations
// in futstats/test/state/app_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i18;

import 'package:futstats/controllers/competition_controller.dart' as _i8;
import 'package:futstats/controllers/match_controller.dart' as _i16;
import 'package:futstats/controllers/objective_controller.dart' as _i14;
import 'package:futstats/controllers/player_controller.dart' as _i11;
import 'package:futstats/controllers/season_controller.dart' as _i7;
import 'package:futstats/models/competition.dart' as _i10;
import 'package:futstats/models/match.dart' as _i17;
import 'package:futstats/models/objective.dart' as _i15;
import 'package:futstats/models/player.dart' as _i13;
import 'package:futstats/models/season.dart' as _i9;
import 'package:futstats/services/repositories/competition_repository.dart'
    as _i4;
import 'package:futstats/services/repositories/match_repository.dart' as _i6;
import 'package:futstats/services/repositories/objective_repository.dart'
    as _i5;
import 'package:futstats/services/repositories/player_repository.dart' as _i2;
import 'package:futstats/services/repositories/season_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlayerRepository_0 extends _i1.SmartFake
    implements _i2.PlayerRepository {
  _FakePlayerRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeasonRepository_1 extends _i1.SmartFake
    implements _i3.SeasonRepository {
  _FakeSeasonRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompetitionRepository_2 extends _i1.SmartFake
    implements _i4.CompetitionRepository {
  _FakeCompetitionRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObjectiveRepository_3 extends _i1.SmartFake
    implements _i5.ObjectiveRepository {
  _FakeObjectiveRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMatchRepository_4 extends _i1.SmartFake
    implements _i6.MatchRepository {
  _FakeMatchRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeasonController_5 extends _i1.SmartFake
    implements _i7.SeasonController {
  _FakeSeasonController_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompetitionController_6 extends _i1.SmartFake
    implements _i8.CompetitionController {
  _FakeCompetitionController_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeason_7 extends _i1.SmartFake implements _i9.Season {
  _FakeSeason_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompetition_8 extends _i1.SmartFake implements _i10.Competition {
  _FakeCompetition_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlayerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerController extends _i1.Mock implements _i11.PlayerController {
  MockPlayerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlayerRepository get playerRepo => (super.noSuchMethod(
        Invocation.getter(#playerRepo),
        returnValue: _FakePlayerRepository_0(
          this,
          Invocation.getter(#playerRepo),
        ),
      ) as _i2.PlayerRepository);

  @override
  _i12.Future<_i13.Player?> loadPlayer(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #loadPlayer,
          [userId],
        ),
        returnValue: _i12.Future<_i13.Player?>.value(),
      ) as _i12.Future<_i13.Player?>);

  @override
  _i12.Future<void> savePlayer(_i13.Player? player) => (super.noSuchMethod(
        Invocation.method(
          #savePlayer,
          [player],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deletePlayer(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deletePlayer,
          [userId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> setCurrentSeason(
    _i13.Player? player,
    String? seasonId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCurrentSeason,
          [
            player,
            seasonId,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [SeasonController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeasonController extends _i1.Mock implements _i7.SeasonController {
  MockSeasonController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SeasonRepository get seasonRepo => (super.noSuchMethod(
        Invocation.getter(#seasonRepo),
        returnValue: _FakeSeasonRepository_1(
          this,
          Invocation.getter(#seasonRepo),
        ),
      ) as _i3.SeasonRepository);

  @override
  _i12.Future<_i9.Season?> loadSeason(String? seasonId) => (super.noSuchMethod(
        Invocation.method(
          #loadSeason,
          [seasonId],
        ),
        returnValue: _i12.Future<_i9.Season?>.value(),
      ) as _i12.Future<_i9.Season?>);

  @override
  _i12.Future<void> saveSeason(_i9.Season? season) => (super.noSuchMethod(
        Invocation.method(
          #saveSeason,
          [season],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteSeason(String? seasonId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSeason,
          [seasonId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<List<_i9.Season>> loadAllSeasons() => (super.noSuchMethod(
        Invocation.method(
          #loadAllSeasons,
          [],
        ),
        returnValue: _i12.Future<List<_i9.Season>>.value(<_i9.Season>[]),
      ) as _i12.Future<List<_i9.Season>>);
}

/// A class which mocks [CompetitionController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompetitionController extends _i1.Mock
    implements _i8.CompetitionController {
  MockCompetitionController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CompetitionRepository get competitionRepo => (super.noSuchMethod(
        Invocation.getter(#competitionRepo),
        returnValue: _FakeCompetitionRepository_2(
          this,
          Invocation.getter(#competitionRepo),
        ),
      ) as _i4.CompetitionRepository);

  @override
  _i12.Future<_i10.Competition?> loadCompetition(String? competitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCompetition,
          [competitionId],
        ),
        returnValue: _i12.Future<_i10.Competition?>.value(),
      ) as _i12.Future<_i10.Competition?>);

  @override
  _i12.Future<void> saveCompetition(_i10.Competition? competition) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCompetition,
          [competition],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteCompetition(String? competitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCompetition,
          [competitionId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<List<_i10.Competition>> loadAllCompetitions() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAllCompetitions,
          [],
        ),
        returnValue:
            _i12.Future<List<_i10.Competition>>.value(<_i10.Competition>[]),
      ) as _i12.Future<List<_i10.Competition>>);
}

/// A class which mocks [ObjectiveController].
///
/// See the documentation for Mockito's code generation for more information.
class MockObjectiveController extends _i1.Mock
    implements _i14.ObjectiveController {
  MockObjectiveController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ObjectiveRepository get objectiveRepo => (super.noSuchMethod(
        Invocation.getter(#objectiveRepo),
        returnValue: _FakeObjectiveRepository_3(
          this,
          Invocation.getter(#objectiveRepo),
        ),
      ) as _i5.ObjectiveRepository);

  @override
  _i12.Future<_i15.Objective?> loadObjective(String? objectiveId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadObjective,
          [objectiveId],
        ),
        returnValue: _i12.Future<_i15.Objective?>.value(),
      ) as _i12.Future<_i15.Objective?>);

  @override
  _i12.Future<void> saveObjective(_i15.Objective? objective) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveObjective,
          [objective],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteObjective(String? objectiveId) => (super.noSuchMethod(
        Invocation.method(
          #deleteObjective,
          [objectiveId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<List<_i15.Objective>> loadAllObjectives() => (super.noSuchMethod(
        Invocation.method(
          #loadAllObjectives,
          [],
        ),
        returnValue:
            _i12.Future<List<_i15.Objective>>.value(<_i15.Objective>[]),
      ) as _i12.Future<List<_i15.Objective>>);
}

/// A class which mocks [MatchController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchController extends _i1.Mock implements _i16.MatchController {
  MockMatchController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.MatchRepository Function(String) get matchRepoFactory =>
      (super.noSuchMethod(
        Invocation.getter(#matchRepoFactory),
        returnValue: (String competitionId) => _FakeMatchRepository_4(
          this,
          Invocation.getter(#matchRepoFactory),
        ),
      ) as _i6.MatchRepository Function(String));

  @override
  _i7.SeasonController get seasonController => (super.noSuchMethod(
        Invocation.getter(#seasonController),
        returnValue: _FakeSeasonController_5(
          this,
          Invocation.getter(#seasonController),
        ),
      ) as _i7.SeasonController);

  @override
  _i8.CompetitionController get competitionController => (super.noSuchMethod(
        Invocation.getter(#competitionController),
        returnValue: _FakeCompetitionController_6(
          this,
          Invocation.getter(#competitionController),
        ),
      ) as _i8.CompetitionController);

  @override
  _i9.Season get season => (super.noSuchMethod(
        Invocation.getter(#season),
        returnValue: _FakeSeason_7(
          this,
          Invocation.getter(#season),
        ),
      ) as _i9.Season);

  @override
  _i10.Competition get competition => (super.noSuchMethod(
        Invocation.getter(#competition),
        returnValue: _FakeCompetition_8(
          this,
          Invocation.getter(#competition),
        ),
      ) as _i10.Competition);

  @override
  List<_i17.Match> get matches => (super.noSuchMethod(
        Invocation.getter(#matches),
        returnValue: <_i17.Match>[],
      ) as List<_i17.Match>);

  @override
  bool get isLoaded => (super.noSuchMethod(
        Invocation.getter(#isLoaded),
        returnValue: false,
      ) as bool);

  @override
  set season(_i9.Season? value) => super.noSuchMethod(
        Invocation.setter(
          #season,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set competition(_i10.Competition? value) => super.noSuchMethod(
        Invocation.setter(
          #competition,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> loadMatches() => (super.noSuchMethod(
        Invocation.method(
          #loadMatches,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> saveMatch(_i17.Match? match) => (super.noSuchMethod(
        Invocation.method(
          #saveMatch,
          [match],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteMatch(String? matchId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMatch,
          [matchId],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
