// Mocks generated by Mockito 5.4.6 from annotations
// in futstats/test/controllers/match_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:futstats/controllers/competition_controller.dart' as _i8;
import 'package:futstats/controllers/season_controller.dart' as _i10;
import 'package:futstats/models/competition.dart' as _i9;
import 'package:futstats/models/match.dart' as _i2;
import 'package:futstats/models/season.dart' as _i11;
import 'package:futstats/services/repositories/competition_repository.dart'
    as _i3;
import 'package:futstats/services/repositories/match_repository.dart' as _i5;
import 'package:futstats/services/repositories/season_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMatch_0 extends _i1.SmartFake implements _i2.Match {
  _FakeMatch_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompetitionRepository_1 extends _i1.SmartFake
    implements _i3.CompetitionRepository {
  _FakeCompetitionRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeasonRepository_2 extends _i1.SmartFake
    implements _i4.SeasonRepository {
  _FakeSeasonRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MatchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatchRepository extends _i1.Mock implements _i5.MatchRepository {
  MockMatchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  _i2.Match fromMap(Map<String, dynamic>? map) => (super.noSuchMethod(
        Invocation.method(
          #fromMap,
          [map],
        ),
        returnValue: _FakeMatch_0(
          this,
          Invocation.method(
            #fromMap,
            [map],
          ),
        ),
      ) as _i2.Match);

  @override
  Map<String, dynamic> toMap(_i2.Match? model) => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [model],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getDocumentId(_i2.Match? model) => (super.noSuchMethod(
        Invocation.method(
          #getDocumentId,
          [model],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getDocumentId,
            [model],
          ),
        ),
      ) as String);

  @override
  _i7.Future<void> set(_i2.Match? model) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [model],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.Match?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i7.Future<_i2.Match?>.value(),
      ) as _i7.Future<_i2.Match?>);

  @override
  _i7.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.Match>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i7.Future<List<_i2.Match>>.value(<_i2.Match>[]),
      ) as _i7.Future<List<_i2.Match>>);
}

/// A class which mocks [CompetitionController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompetitionController extends _i1.Mock
    implements _i8.CompetitionController {
  MockCompetitionController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CompetitionRepository get competitionRepo => (super.noSuchMethod(
        Invocation.getter(#competitionRepo),
        returnValue: _FakeCompetitionRepository_1(
          this,
          Invocation.getter(#competitionRepo),
        ),
      ) as _i3.CompetitionRepository);

  @override
  _i7.Future<_i9.Competition?> loadCompetition(String? competitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadCompetition,
          [competitionId],
        ),
        returnValue: _i7.Future<_i9.Competition?>.value(),
      ) as _i7.Future<_i9.Competition?>);

  @override
  _i7.Future<void> saveCompetition(_i9.Competition? competition) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCompetition,
          [competition],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteCompetition(String? competitionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCompetition,
          [competitionId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i9.Competition>> loadAllCompetitions() =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAllCompetitions,
          [],
        ),
        returnValue:
            _i7.Future<List<_i9.Competition>>.value(<_i9.Competition>[]),
      ) as _i7.Future<List<_i9.Competition>>);
}

/// A class which mocks [SeasonController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeasonController extends _i1.Mock implements _i10.SeasonController {
  MockSeasonController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SeasonRepository get seasonRepo => (super.noSuchMethod(
        Invocation.getter(#seasonRepo),
        returnValue: _FakeSeasonRepository_2(
          this,
          Invocation.getter(#seasonRepo),
        ),
      ) as _i4.SeasonRepository);

  @override
  _i7.Future<_i11.Season?> loadSeason(String? seasonId) => (super.noSuchMethod(
        Invocation.method(
          #loadSeason,
          [seasonId],
        ),
        returnValue: _i7.Future<_i11.Season?>.value(),
      ) as _i7.Future<_i11.Season?>);

  @override
  _i7.Future<void> saveSeason(_i11.Season? season) => (super.noSuchMethod(
        Invocation.method(
          #saveSeason,
          [season],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteSeason(String? seasonId) => (super.noSuchMethod(
        Invocation.method(
          #deleteSeason,
          [seasonId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.Season>> loadAllSeasons() => (super.noSuchMethod(
        Invocation.method(
          #loadAllSeasons,
          [],
        ),
        returnValue: _i7.Future<List<_i11.Season>>.value(<_i11.Season>[]),
      ) as _i7.Future<List<_i11.Season>>);
}
