// Mocks generated by Mockito 5.4.6 from annotations
// in futstats/test/controllers/simple_controllers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:futstats/models/competition.dart' as _i4;
import 'package:futstats/models/objective.dart' as _i5;
import 'package:futstats/models/player.dart' as _i2;
import 'package:futstats/models/season.dart' as _i3;
import 'package:futstats/services/repositories/competition_repository.dart'
    as _i10;
import 'package:futstats/services/repositories/objective_repository.dart'
    as _i11;
import 'package:futstats/services/repositories/player_repository.dart' as _i6;
import 'package:futstats/services/repositories/season_repository.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlayer_0 extends _i1.SmartFake implements _i2.Player {
  _FakePlayer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeason_1 extends _i1.SmartFake implements _i3.Season {
  _FakeSeason_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompetition_2 extends _i1.SmartFake implements _i4.Competition {
  _FakeCompetition_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObjective_3 extends _i1.SmartFake implements _i5.Objective {
  _FakeObjective_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlayerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerRepository extends _i1.Mock implements _i6.PlayerRepository {
  MockPlayerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  _i2.Player fromMap(Map<String, dynamic>? map) => (super.noSuchMethod(
        Invocation.method(
          #fromMap,
          [map],
        ),
        returnValue: _FakePlayer_0(
          this,
          Invocation.method(
            #fromMap,
            [map],
          ),
        ),
      ) as _i2.Player);

  @override
  Map<String, dynamic> toMap(_i2.Player? model) => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [model],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getDocumentId(_i2.Player? model) => (super.noSuchMethod(
        Invocation.method(
          #getDocumentId,
          [model],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDocumentId,
            [model],
          ),
        ),
      ) as String);

  @override
  _i8.Future<void> set(_i2.Player? model) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [model],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.Player?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i8.Future<_i2.Player?>.value(),
      ) as _i8.Future<_i2.Player?>);

  @override
  _i8.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.Player>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i8.Future<List<_i2.Player>>.value(<_i2.Player>[]),
      ) as _i8.Future<List<_i2.Player>>);
}

/// A class which mocks [SeasonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeasonRepository extends _i1.Mock implements _i9.SeasonRepository {
  MockSeasonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  _i3.Season fromMap(Map<String, dynamic>? map) => (super.noSuchMethod(
        Invocation.method(
          #fromMap,
          [map],
        ),
        returnValue: _FakeSeason_1(
          this,
          Invocation.method(
            #fromMap,
            [map],
          ),
        ),
      ) as _i3.Season);

  @override
  Map<String, dynamic> toMap(_i3.Season? model) => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [model],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getDocumentId(_i3.Season? model) => (super.noSuchMethod(
        Invocation.method(
          #getDocumentId,
          [model],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDocumentId,
            [model],
          ),
        ),
      ) as String);

  @override
  _i8.Future<void> set(_i3.Season? model) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [model],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i3.Season?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i8.Future<_i3.Season?>.value(),
      ) as _i8.Future<_i3.Season?>);

  @override
  _i8.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.Season>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i8.Future<List<_i3.Season>>.value(<_i3.Season>[]),
      ) as _i8.Future<List<_i3.Season>>);
}

/// A class which mocks [CompetitionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompetitionRepository extends _i1.Mock
    implements _i10.CompetitionRepository {
  MockCompetitionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  _i4.Competition fromMap(Map<String, dynamic>? map) => (super.noSuchMethod(
        Invocation.method(
          #fromMap,
          [map],
        ),
        returnValue: _FakeCompetition_2(
          this,
          Invocation.method(
            #fromMap,
            [map],
          ),
        ),
      ) as _i4.Competition);

  @override
  Map<String, dynamic> toMap(_i4.Competition? model) => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [model],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getDocumentId(_i4.Competition? model) => (super.noSuchMethod(
        Invocation.method(
          #getDocumentId,
          [model],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDocumentId,
            [model],
          ),
        ),
      ) as String);

  @override
  _i8.Future<void> set(_i4.Competition? model) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [model],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i4.Competition?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i8.Future<_i4.Competition?>.value(),
      ) as _i8.Future<_i4.Competition?>);

  @override
  _i8.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Competition>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i8.Future<List<_i4.Competition>>.value(<_i4.Competition>[]),
      ) as _i8.Future<List<_i4.Competition>>);
}

/// A class which mocks [ObjectiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockObjectiveRepository extends _i1.Mock
    implements _i11.ObjectiveRepository {
  MockObjectiveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  _i5.Objective fromMap(Map<String, dynamic>? map) => (super.noSuchMethod(
        Invocation.method(
          #fromMap,
          [map],
        ),
        returnValue: _FakeObjective_3(
          this,
          Invocation.method(
            #fromMap,
            [map],
          ),
        ),
      ) as _i5.Objective);

  @override
  Map<String, dynamic> toMap(_i5.Objective? model) => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [model],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getDocumentId(_i5.Objective? model) => (super.noSuchMethod(
        Invocation.method(
          #getDocumentId,
          [model],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDocumentId,
            [model],
          ),
        ),
      ) as String);

  @override
  _i8.Future<void> set(_i5.Objective? model) => (super.noSuchMethod(
        Invocation.method(
          #set,
          [model],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.Objective?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i8.Future<_i5.Objective?>.value(),
      ) as _i8.Future<_i5.Objective?>);

  @override
  _i8.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i5.Objective>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i8.Future<List<_i5.Objective>>.value(<_i5.Objective>[]),
      ) as _i8.Future<List<_i5.Objective>>);
}
