// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWD7iGND-vtO-_ln7dElLgexIwTKAdJl0',
    appId: '1:512480832773:android:6de80cd3364f70fe7a9b6c',
    messagingSenderId: '512480832773',
    projectId: 'futstats-firebase-4c9b5',
    storageBucket: 'futstats-firebase-4c9b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4x7WoYnoPMNbapaQ-uDRWL4zBx5y2VhY',
    appId: '1:512480832773:ios:89664a9dc9fc69907a9b6c',
    messagingSenderId: '512480832773',
    projectId: 'futstats-firebase-4c9b5',
    storageBucket: 'futstats-firebase-4c9b5.firebasestorage.app',
    iosBundleId: 'com.example.futstats',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9DOMFainsngmAdrE-6fxbqrtZ-dR5hLQ',
    appId: '1:512480832773:web:a63be46570e80c247a9b6c',
    messagingSenderId: '512480832773',
    projectId: 'futstats-firebase-4c9b5',
    authDomain: 'futstats-firebase-4c9b5.firebaseapp.com',
    storageBucket: 'futstats-firebase-4c9b5.firebasestorage.app',
  );

}